version: '3.7'

networks:
  my_network:
    name: 'my_network'

services:
  postgis:
    container_name: 'postgis_container'
    image: pgrouting/pgrouting:12-3.0-3.0.1
    networks:
      - my_network
    volumes:
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/db/:/db/
    env_file:
      - ./.env
    ports:
      - 25432:5432
