version: '3.7'

networks:
  my_network:
    name: 'my_network'

services:
  postgis:
    container_name: 'postgis_container'
    image: kartoza/postgis:13.0
    networks:
      - my_network
    volumes:
      - ./db/:/var/lib/postgresql
    env_file:
      - ./.env
    ports:
      - 25432:5432